apiVersion: v1
kind: Service
metadata:
  name: py-app-svc
  namespace: default
  labels:
    app: py-app
spec:
  type: NodePort 
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000  # Adjust if your Node.js app is running on a different port
      nodePort: 30008
  selector:
    app: py-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
  namespace: default
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
      - name: py-app
        image: bjnandi/python-crud-app:v1.0.2
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST  
          value: postgresql.default.svc.cluster.local

        - name: POSTGRES_DB
          value: crud

        - name: POSTGRES_USER
          value: postgres

        - name: POSTGRES_PASSWORD
          #value: "5isBt7ezr2"
          valueFrom:
              secretKeyRef:
                name: pg-password-secret  # The name of your Secret
                key: postgres-password  # The key in the Secret containing the password