apiVersion: v1
kind: Service
metadata:
  name: postgresql  # Service name
  namespace: default
  labels:
    app: postgresql
spec:
  ports:
  - port: 5432  # PostgreSQL default port
    name: postgres
  clusterIP: None  # Headless service
  selector:
    app: postgresql

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql  # Name of the StatefulSet
  namespace: default
  labels:
    app: postgresql
spec:
  serviceName: "postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: crud

        - name: POSTGRES_USER
          value: "postgres" # Replace with your PostgreSQL username

        - name: POSTGRES_PASSWORD
          valueFrom:
              secretKeyRef:
                name: pg-password-secret  # The name of your Secret
                key: postgres-password  # The key in the Secret containing the password

        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data  # PostgreSQL's default data directory

      # volumes:
      # - name: postgres-data
      #   persistentVolumeClaim:
      #     claimName: postgres-pvc  # The name of your PVC

  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi  # Adjust the size as needed
      storageClassName: local-storage  # Ensure this matches your StorageClass