apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-init-configmap
data:
  init-db.sql: |
    -- Create the database if it doesn't already exist
    CREATE DATABASE crud;

    -- Connect to the 'crud' database
    \connect crud;

    -- Create the 'students' table
    CREATE TABLE students (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL,
      phone VARCHAR(255) NOT NULL
    );

    -- Insert initial data into the 'students' table
    INSERT INTO students (id, name, email, phone) VALUES
    (1, 'Aarav Chauhan', 'aaravchauhan2211@gmail.com', '7310628048');
