apiVersion: v1
kind: Secret
metadata:
  name: pg-password-secret  # Name of the secret
  namespace: default        # Specify the namespace, change if needed
  annotations:
    "helm.sh/resource-policy": keep  # Prevents Helm from deleting this resource
type: Opaque
data:
  postgres-password: cGFzc3dvcmQ=  # Base64 encoded password ("password" is used here as an example)
